/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "UserVisits-devenv",
            "region": "us-east-1"
        }
    ],
    "aws_user_files_s3_bucket": "glidaadotcom211606-devenv",
    "aws_user_files_s3_bucket_region": "us-east-1",
    "aws_cloud_logic_custom": [
        {
            "name": "api2899b73b",
            "endpoint": "https://sehfwd1zvl.execute-api.us-east-1.amazonaws.com/devenv",
            "region": "us-east-1"
        }
    ],
    "aws_appsync_graphqlEndpoint": "https://b2zvjblsdrep3drvpnidki2iym.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-yax4qu5isnf63bnuv67zmip7s4",
    "aws_cognito_identity_pool_id": "us-east-1:7e440566-e3de-44eb-bd28-0340eaeea4c0",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_R1bfvav3v",
    "aws_user_pools_web_client_id": "1i8go01khi9edd784mpgvi0069",
    "oauth": {}
};


export default awsmobile;
